### ISSUE TITLE
L6218E: Undefined symbol asm (referred from ad9833.o)

### ISSUE THREAD

**Issue by eaz-sudo** [Bardia-Afshar/AD9833-STM32#1]
Hi I have this problem when I want compile the code in keil ide my current micro is stm32f103c8t6 what should i do with this error

**Comment by Bardia-Afshar** [comment]
In the code, I used assembly code "nope" for timing purposes, generating a delay. However, there seems to be a discrepancy between the "nope" instruction in Keil IDE (which I'm unfamiliar with) and GCC. I suggest either finding a code for assembly nop for Keil IDE or using a traditional delay method.
